# REDDIT INFO
REDDIT_CLIENT_SECRET = "Bz48bbfbycZif6kH3UarB8dYW6Ireg" # API KEY
REDDIT_USER_AGENT = "testing" # APP NAME
REDDIT_USERNAME = "Dry_Gas3311"
REDDIT_REDIRECT_URI = "http://localhost:8080"
REDDIT_CLIENT_ID = "RtwgbCMW3W0sFw"

# POSTGRESQL ACCOUNT INFO: 
POSTGRESQL_MAIN_USERNAME = 'FiB112358!#'
POSTGRESQL_PORT = "5432"
POSTGRESQL_HOST = 'localhost'
POSTGRESQL_USERNAME = 'ghost-postgres'

# TDA
TDA_USERNAME = 'CMWolfe922'
TDA_PASSWORD = 'FIB112358'
TDA_DEV_EMAIL = 'cmwolfe1123@gmail.com'
TDA_DEV_PASSWORD = 'FIBdev112358'
TDA_APIKEY = 'C1TEUG4JBLJU89X2GDXQ2RHHGUYX0XUZ'
TDA_CONSUMER_ID = '498282935'
TDA_REDIRECT_URI = 'https://localhost'

# MYSQL
MYSQL_USERNAME = "root"
MYSQL_HOST = "localhost"
MYSQL_PORT = "3306"
